const POST = {
  LOAD: "POST_LOAD",
  LOAD_SUCCESS: "POST_LOAD_SUCCESS",
  LOAD_FAIL: "POST_LOAD_FAIL"
};
const LOGIN = {
  LOADING: "LOGIN_LOADING",
  SUCCESS: "LOGIN_SUCCESS",
  FAIL: "LOGIN_FAIL"
};

const SIGNUP = {
  LOADING: "SIGNUP_LOADING",
  SUCCESS: "SIGNUP_SUCCESS",
  FAIL: "SIGNUP_FAIL"
};

const PROFILE = {
  LOADING: "PROFILE_LOADING",
  SUCCESS: "PROFILE_SUCCESS",
  FAIL: "PROFILE_FAIL"
};

const POSTDATA = {
  LOADING: "DATA_LOADING",
  SUCCESS: "DATA_SUCCESS",
  FAIL: "DATA_FAIL"
};

export { POST, LOGIN, SIGNUP, PROFILE, POSTDATA };
